### ISSUE TITLE
Issue when installing with SPM

### ISSUE THREAD

**Issue by twittemb** [flagship-io/flagship-ios#19]
Hi,

I'm having compilation errors when integrating the SDK with SPM.
My project is pretty simple since it is an empty SwiftUI project.
I'm just adding the following SPM: `https://github.com/flagship-io/flagship-ios.git` and linking `Flagship` to my only target.

It fails to compile with several errors like this one:

```
Multiple commands produce '~/Library/Developer/Xcode/DerivedData/Flagship-bmnssvjueqaxrjcenllotycnjmdi/Build/Intermediates.noindex/Flagship.build/Debug-iphonesimulator/Flagship.build/Objects-normal/arm64/Flagship.LinkFileList'
```

I tried to install the XCFramework, but the link provided in the doc is broken -> `http://sdk.abtasty.com/ios/Flagship.xcframework.zip`

**Comment by twittemb** [comment]
It was an issue on my side, never mind !

**Comment by ABTastyAdel** [comment]
Hello @twittemb, Okay 👍 and thank you for your interest.
